# Generated by Django 5.0.7 on 2024-08-19 21:09

import performance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadCSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_weight', models.PositiveIntegerField(validators=[performance.models.validate_to_weight])),
                ('fuel_capacity', models.PositiveIntegerField(validators=[performance.models.validate_fuel_capacity])),
                ('to_heading', models.PositiveIntegerField(validators=[performance.models.validate_heading])),
                ('to_length', models.PositiveIntegerField(validators=[performance.models.validate_runway_length])),
                ('to_condition', models.CharField(max_length=2, validators=[performance.models.validate_runway_condition])),
                ('to_press_alt', models.PositiveIntegerField(validators=[performance.models.validate_pressure_altitude])),
                ('to_temp', models.IntegerField(validators=[performance.models.validate_temperature])),
                ('to_wind_speed', models.PositiveIntegerField(validators=[performance.models.validate_wind_speed])),
                ('to_wind_direction', models.PositiveIntegerField(validators=[performance.models.validate_wind_direction])),
                ('travel_dist', models.PositiveIntegerField(validators=[performance.models.validate_travel_distance])),
                ('cr_heading', models.PositiveIntegerField(validators=[performance.models.validate_heading])),
                ('cr_press_alt', models.PositiveIntegerField(validators=[performance.models.validate_pressure_altitude])),
                ('cr_temp', models.IntegerField(validators=[performance.models.validate_temperature])),
                ('cr_wind_speed', models.PositiveIntegerField(validators=[performance.models.validate_wind_speed])),
                ('cr_wind_direction', models.PositiveIntegerField(validators=[performance.models.validate_wind_direction])),
                ('cr_power', models.PositiveIntegerField(validators=[performance.models.validate_cruise_rpm])),
                ('land_heading', models.PositiveIntegerField(validators=[performance.models.validate_heading])),
                ('land_length', models.PositiveIntegerField(validators=[performance.models.validate_runway_length])),
                ('land_condition', models.CharField(max_length=2, validators=[performance.models.validate_runway_condition])),
                ('land_press_alt', models.PositiveIntegerField(validators=[performance.models.validate_pressure_altitude])),
                ('land_temp', models.IntegerField(validators=[performance.models.validate_temperature])),
                ('land_wind_speed', models.PositiveIntegerField(validators=[performance.models.validate_wind_speed])),
                ('land_wind_direction', models.PositiveIntegerField(validators=[performance.models.validate_wind_direction])),
            ],
        ),
    ]
